using MicroERP.Application.Features.EmployeeAttendance.Attendance.DTOs.Overtime;
using MicroERP.Application.Features.EmployeeAttendance.Attendance.Interfaces;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace MicroERP.Application.Features.Payrolls.Reports.Queries;

public class EmployeeOvertimePdfService
    : IEmployeeOvertimePdfService
{
    private readonly IOvertimeReportQueries _queries;

    public EmployeeOvertimePdfService(
        IOvertimeReportQueries queries)
    {
        _queries = queries;
    }

    public async Task<byte[]> GenerateAsync(
        OvertimeReportFilterDto filter,
        CancellationToken cancellationToken = default)
    {
        var result =
            await _queries.GetOvertimeReportAsync(
                filter,
                cancellationToken);

        if (!result.Success || result.Data == null)
        {
            throw new InvalidOperationException(
                result.Message ??
                "Overtime report was not found.");
        }

        var report = result.Data;

        if (report.Overtimes.Count == 0)
        {
            throw new InvalidOperationException(
                "No overtime records found.");
        }

        var document =
            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(
                        PageSizes.A4.Landscape());

                    page.Margin(30);

                    page.DefaultTextStyle(
                        x => x.FontSize(9));

                    page.Content()
               .Element(x =>
                   ComposeContent(
                       x,
                       report,
                       filter));

                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by Micro ERP")
                        .FontSize(8);
                });
            });

        return document.GeneratePdf();
    }

    // =========================================================
    // HEADER
    // =========================================================

    private static void ComposeHeader(
        IContainer container,
        OvertimeReportFilterDto filter)
    {
        container.Column(column =>
        {
            column.Item()
                .AlignCenter()
                .Text("OVERTIME REPORT")
                .Bold()
                .FontSize(18);

            if (filter.FromDate.HasValue ||
                filter.ToDate.HasValue)
            {
                column.Item()
                    .PaddingTop(5)
                    .AlignCenter()
                    .Text(
                        $"Period: " +
                        $"{filter.FromDate:yyyy-MM-dd}" +
                        " - " +
                        $"{filter.ToDate:yyyy-MM-dd}")
                    .FontSize(9);
            }
        });
    }

    // =========================================================
    // CONTENT
    // =========================================================

    private static void ComposeContent(
    IContainer container,
    OvertimeReportResultDto report,
    OvertimeReportFilterDto filter)
    {
        var isGroupedReport =
            !filter.EmployeeId.HasValue;

        container.Column(column =>
        {
            column.Spacing(15);

            column.Item()
                .Element(x =>
                    ComposeHeader(
                        x,
                        filter));

            if (isGroupedReport)
            {
                ComposeGroupedByEmployee(
                    column,
                    report.Overtimes);
            }
            else
            {
                if (report.Overtimes.Count > 0)
                {
                    column.Item()
                    .Element(x =>
                        ComposeEmployeeSection(
                            x,
                            report.Overtimes.First().EmployeeName,
                            report.Overtimes.First().Department,
                            report.Overtimes
                                .OrderBy(x => x.StartDateTime)
                                .ToList()));
                }
                else
                {
                    column.Item()
                        .Text("No overtime records found.");
                }
               
            }

            column.Item()
                .ShowEntire()
                .Element(x =>
                    ComposeTotals(
                        x,
                        report));
        });
    }

    // =========================================================
    // GROUP BY EMPLOYEE
    // =========================================================

    private static void ComposeGroupedByEmployee(
       ColumnDescriptor column,
       List<OvertimeReportDto> data)
    {
        var groups =
            data
                .GroupBy(x => new
                {
                    x.EmployeeId,
                    x.EmployeeName,
                    x.Department
                })
                .OrderBy(x => x.Key.EmployeeName);

        foreach (var group in groups)
        {
            var employeeData =
                group
                    .OrderBy(x => x.StartDateTime)
                    .ToList();

            column.Item()
                .ShowEntire()
                .Element(x =>
                    ComposeEmployeeSection(
                        x,
                        group.Key.EmployeeName,
                        group.Key.Department,
                        employeeData));
        }
    }

    // =========================================================
    // EMPLOYEE SECTION
    // =========================================================

    private static void ComposeEmployeeSection(
      IContainer container,
      string employeeName,
      string? department,
      List<OvertimeReportDto> data)
    {
        container.Column(column =>
        {
            column.Item()
                .PaddingBottom(6)
                .DefaultTextStyle(x => x.FontSize(11))
                .Text(text =>
                {
                    text.Span("Employee: ")
                        .Bold();

                    text.Span(employeeName);

                    if (!string.IsNullOrWhiteSpace(department))
                    {
                        text.Span("    ");

                        text.Span("Department: ")
                            .Bold();

                        text.Span(department);
                    }
                });

            column.Item()
                .Element(x =>
                    ComposeOvertimeTable(
                        x,
                        data));
        });
    }

    // =========================================================
    // OVERTIME TABLE
    // =========================================================

    private static void ComposeOvertimeTable(
        IContainer container,
        List<OvertimeReportDto> data)
    {
        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.ConstantColumn(70);   // Date
                columns.ConstantColumn(60);   // Start
                columns.ConstantColumn(60);   // End
                columns.ConstantColumn(70);   // Hours
                columns.RelativeColumn(1);     // Rate
                columns.ConstantColumn(75);    // Multiplier
                columns.RelativeColumn(1);     // Amount
                columns.RelativeColumn(1);     // Type
                columns.RelativeColumn(1);     // Status
                columns.RelativeColumn(1);     // Paid
            });

            table.Header(header =>
            {
                AddHeaderCell(
                    header.Cell(),
                    "Date");

                AddHeaderCell(
                    header.Cell(),
                    "Start");

                AddHeaderCell(
                    header.Cell(),
                    "End");

                AddHeaderCell(
                    header.Cell(),
                    "Hours");

                AddHeaderCell(
                    header.Cell(),
                    "Hourly Rate");

                AddHeaderCell(
                    header.Cell(),
                    "Multiplier");

                AddHeaderCell(
                    header.Cell(),
                    "Amount");

                AddHeaderCell(
                    header.Cell(),
                    "Type");

                AddHeaderCell(
                    header.Cell(),
                    "Status");

                AddHeaderCell(
                    header.Cell(),
                    "Paid");
            });

            foreach (var overtime in
                data.OrderBy(x => x.StartDateTime))
            {
                AddBodyCell(
                    table,
                    overtime.StartDateTime
                        .ToString("yyyy-MM-dd"));

                AddBodyCell(
                    table,
                    overtime.StartDateTime
                        .ToString("HH:mm"));

                AddBodyCell(
                    table,
                    overtime.EndDateTime
                        .ToString("HH:mm"));

                AddAmountCell(
                    table,
                    overtime.TotalHours);

                AddAmountCell(
                    table,
                    overtime.HourlyRate);

                AddAmountCell(
                    table,
                    overtime.Multiplier);

                AddAmountCell(
                    table,
                    overtime.Amount);

                AddBodyCell(
                    table,
                    overtime.Type.ToString());

                AddBodyCell(
                    table,
                    overtime.Status.ToString());

                AddBodyCell(
                    table,
                    overtime.IsPaid
                        ? "Paid"
                        : "Unpaid");
            }
        });
    }

    // =========================================================
    // TOTALS
    // =========================================================

    private static void ComposeTotals(
     IContainer container,
     OvertimeReportResultDto report)
    {
        container
            .PaddingTop(10)
            .Column(column =>
            {
                column.Item()
                    .Text("OVERTIME SUMMARY")
                    .Bold()
                    .FontSize(12);

                column.Item()
                    .PaddingTop(8)
                    .Row(row =>
                    {
                        row.RelativeItem()
    .Element(x =>
        AddTotalCell(
            x,
            "Records",
            report.RecordsCount.ToString("N0")));

                        row.RelativeItem()
                            .Element(x =>
                                AddTotalCell(
                                    x,
                                    "Employees",
                                    report.EmployeesCount.ToString("N0")));

                        row.RelativeItem()
                            .Element(x =>
                                AddTotalCell(
                                    x,
                                    "Total Hours",
                                    report.TotalHours.ToString("N2")));

                        row.RelativeItem()
                            .Element(x =>
                                AddTotalCell(
                                    x,
                                    "Total Amount",
                                    report.TotalAmount.ToString("N2")));

                        row.RelativeItem()
                            .Element(x =>
                                AddTotalCell(
                                    x,
                                    "Paid Amount",
                                    report.PaidAmount.ToString("N2")));
                    });
            });
    }

    // =========================================================
    // BODY CELL
    // =========================================================

    private static void AddHeaderCell(
      IContainer cell,
      string value)
    {
        cell
            .Background(Colors.Grey.Lighten2)
            .Border(1)
            .PaddingVertical(6)
            .PaddingHorizontal(5)
            .AlignMiddle()
            .AlignCenter()
            .Text(value)
            .Bold();
    }

    private static void AddBodyCell(
        TableDescriptor table,
        string value)
    {
        table.Cell()
            .BorderBottom(1)
            .PaddingVertical(6)
            .PaddingHorizontal(5)
            .AlignMiddle()
            .AlignCenter()
            .Text(value);
    }

    private static void AddAmountCell(
        TableDescriptor table,
        decimal value)
    {
        table.Cell()
            .BorderBottom(1)
            .PaddingVertical(6)
            .PaddingHorizontal(5)
            .AlignMiddle()
            .AlignRight()
            .Text(value.ToString("N2"));
    }

    // =========================================================
    // TOTAL CELL
    // =========================================================

    private static IContainer AddTotalCell(
    IContainer container,
    string label,
    string value)
    {
        container
            .Background(Colors.Grey.Lighten2)
            .Border(1)
            .Padding(8)
            .Column(column =>
            {
                column.Item()
                    .AlignCenter()
                    .Text(label)
                    .Bold();

                column.Item()
                    .PaddingTop(4)
                    .AlignCenter()
                    .Text(value)
                    .Bold();
            });

        return container;
    }
}