using MicroERP.Application.Features.Payrolls.Reports.DTOs;
using MicroERP.Application.Features.Payrolls.Reports.Interfaces;
using QuestPDF.Elements.Table;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using QuestContainer = QuestPDF.Infrastructure.IContainer;

namespace MicroERP.Application.Features.Payrolls.Reports.Queries;

public class EmployeePayrollHistoryPdfService
    : IEmployeePayrollHistoryPdfService
{
    private readonly IPayrollReportQueries _queries;

    public EmployeePayrollHistoryPdfService(
        IPayrollReportQueries queries)
    {
        _queries = queries;
    }

    public async Task<byte[]> GenerateAsync(
        EmployeePayrollHistoryFilterDto filter,
        CancellationToken cancellationToken = default)
    {
        var result =
            await _queries.GetEmployeePayrollHistoryAsync(
                filter,
                cancellationToken);

        if (!result.Success || result.Data == null)
        {
            throw new InvalidOperationException(
                result.Message ??
                "Employee payroll history was not found.");
        }

        var data = result.Data;

        if (data.Count == 0)
        {
            throw new InvalidOperationException(
                "No payroll history found for this employee.");
        }

        var employee = data.First();

        var document =
            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4.Landscape());

                    page.Margin(30);

                    page.DefaultTextStyle(
                        x => x.FontSize(9));

                    page.Header()
                        .Element(x =>
                            ComposeHeader(
                                x));

                    page.Content()
                        .Element(x =>
                            ComposeContent(
                                x,
                                data));

                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by Micro ERP");
                });
            });

        return document.GeneratePdf();
    }

    // =========================================================
    // HEADER
    // =========================================================

    private static void ComposeHeader(
        QuestContainer container)
    {
        container
            .AlignCenter()
            .Text("EMPLOYEE PAYROLL HISTORY")
            .Bold()
            .FontSize(18);
    }

    // =========================================================
    // CONTENT
    // =========================================================

    private static void ComposeContent(
        QuestContainer container,
        List<EmployeePayrollHistoryDto> data)
    {
        var employee = data.First();

        container.Column(column =>
        {
            column.Spacing(15);

            // Employee Information
            column.Item()
                .Element(x =>
                    ComposeEmployeeInformation(
                        x,
                        employee));

            // Payroll History
            column.Item()
                .Element(x =>
                    ComposeHistoryTable(
                        x,
                        data));

            // Totals
            column.Item()
                .Element(x =>
                    ComposeTotals(
                        x,
                        data));
        });
    }

    // =========================================================
    // EMPLOYEE INFORMATION
    // =========================================================

    private static void ComposeEmployeeInformation(
      QuestContainer container,
      EmployeePayrollHistoryDto employee)
    {
        container
            .Border(1)
            .Padding(10)
            .Text(text =>
            {
                text.Span("Employee: ")
                    .Bold();

                text.Span(employee.EmployeeName);

                text.Span("    ");

                text.Span("Department: ")
                    .Bold();

                text.Span(employee.Department);

                text.Span("    ");

                text.Span("Hire Date: ")
                    .Bold();

                text.Span(
                    employee.HireDate
                        .ToString("yyyy-MM-dd"));
            });
    }

    // =========================================================
    // PAYROLL HISTORY
    // =========================================================

    private static void ComposeHistoryTable(
        QuestContainer container,
        List<EmployeePayrollHistoryDto> data)
    {
        container.Column(column =>
        {
            column.Item()
                .Text("PAYROLL HISTORY")
                .Bold()
                .FontSize(12);

            column.Item()
                .PaddingTop(8)
                .Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.ConstantColumn(65);
                        columns.RelativeColumn(1.2f);
                        columns.RelativeColumn(1.2f);
                        columns.RelativeColumn(1.2f);
                        columns.RelativeColumn(1.2f);
                        columns.RelativeColumn(1.2f);
                        columns.RelativeColumn(1);
                    });
                    table.Header(header =>
                    {
                        header.Cell()
                            .Element(HeaderCellStyle)
                            .AlignCenter()
                            .Text("Period");

                        header.Cell()
                            .Element(HeaderCellStyle)
                            .AlignCenter()
                            .Text("Gross Salary");

                        header.Cell()
                            .Element(HeaderCellStyle)
                            .AlignCenter()
                            .Text("Allowances");

                        header.Cell()
                            .Element(HeaderCellStyle)
                            .AlignCenter()
                            .Text("Overtime");

                        header.Cell()
                            .Element(HeaderCellStyle)
                            .AlignCenter()
                            .Text("Deductions");

                        header.Cell()
                            .Element(HeaderCellStyle)
                            .AlignCenter()
                            .Text("Net Salary");

                        header.Cell()
                            .Element(HeaderCellStyle)
                            .AlignCenter()
                            .Text("Status");
                    });

                    foreach (var payroll in data)
                    {
                        AddBodyCell(
                            table,
                            $"{payroll.Year}-{payroll.Month:00}");

                        AddAmountCell(
                            table,
                            payroll.GrossSalary);

                        AddAmountCell(
                            table,
                            payroll.TotalAllowances);

                        AddAmountCell(
                            table,
                            payroll.TotalOvertime);

                        AddAmountCell(
                            table,
                            payroll.TotalDeductions);

                        AddAmountCell(
                            table,
                            payroll.NetSalary);

                        AddBodyCell(
                            table,
                            payroll.Status.ToString());
                    }
                });
        });
    }

    // =========================================================
    // TOTALS
    // =========================================================

    private static void ComposeTotals(
       QuestContainer container,
       List<EmployeePayrollHistoryDto> data)
    {
        var totalGrossSalary =
            data.Sum(x => x.GrossSalary);

        var totalAllowances =
            data.Sum(x => x.TotalAllowances);

        var totalOvertime =
            data.Sum(x => x.TotalOvertime);

        var totalDeductions =
            data.Sum(x => x.TotalDeductions);

        var totalNetSalary =
            data.Sum(x => x.NetSalary);

        container
            .PaddingTop(5)
            .Column(column =>
            {
                column.Item()
                    .Text("SALARY SUMMARY")
                    .Bold()
                    .FontSize(12);

                column.Item()
                    .PaddingTop(8)
                    .Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                        });

                        AddTotalCell(
                            table,
                            "Total Gross Salary",
                            totalGrossSalary);

                        AddTotalCell(
                            table,
                            "Total Allowances",
                            totalAllowances);

                        AddTotalCell(
                            table,
                            "Total Overtime",
                            totalOvertime);

                        AddTotalCell(
                            table,
                            "Total Deductions",
                            totalDeductions);

                        AddTotalCell(
                            table,
                            "Total Net Salary",
                            totalNetSalary);
                    });
            });
    }

    // =========================================================
    // STYLES
    // =========================================================

    private static IContainer HeaderCellStyle(
     IContainer container)
    {
        return container
            .Background(Colors.Grey.Lighten2)
            .Border(1)
            .PaddingVertical(6)
            .PaddingHorizontal(5)
            .AlignMiddle();
    }

    private static void AddBodyCell(
     TableDescriptor table,
     string value)
    {
        table.Cell()
            .BorderBottom(1)
            .PaddingVertical(6)
            .PaddingHorizontal(5)
            .AlignMiddle()
            .AlignCenter()
            .Text(value);
    }

    private static void AddAmountCell(
        TableDescriptor table,
        decimal value)
    {
        table.Cell()
            .BorderBottom(1)
            .PaddingVertical(6)
            .PaddingHorizontal(5)
            .AlignMiddle()
            .AlignRight()
            .Text(value.ToString("N2"));
    }

    private static void AddTotalCell(
    TableDescriptor table,
    string label,
    decimal value)
    {
        table.Cell()
            .Background(Colors.Grey.Lighten2)
            .Border(1)
            .Padding(8)
            .Column(column =>
            {
                column.Item()
                    .AlignCenter()
                    .Text(label)
                    .Bold();

                column.Item()
                    .PaddingTop(5)
                    .AlignCenter()
                    .Text(value.ToString("N2"))
                    .Bold();
            });
    }
}