using MicroERP.Application.Features.Payrolls.Reports.DTOs;
using MicroERP.Application.Features.Payrolls.Reports.Interfaces;
using MicroERP.Domin.Enums;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestContainer = QuestPDF.Infrastructure.IContainer;
namespace MicroERP.Application.Features.Payrolls.Reports.Queries
{

    public class EmployeePayslipPdfService
        : IEmployeePayslipPdfService
    {
        private readonly IPayrollReportQueries _queries;

        public EmployeePayslipPdfService(
            IPayrollReportQueries queries)
        {
            _queries = queries;
        }

        public async Task<byte[]> GenerateAsync(
            int payrollId,
            CancellationToken cancellationToken = default)
        {
            var result =
                await _queries.GetEmployeePayslipAsync(
                    payrollId,
                    cancellationToken);

            if (!result.Success || result.Data == null)
            {
                throw new InvalidOperationException(
                    result.Message ?? "Payslip was not found.");
            }

            var payslip = result.Data;

            var document =
                Document.Create(container =>
                {
                    container.Page(page =>
                    {
                        page.Size(PageSizes.A4);

                        page.Margin(35);

                        page.DefaultTextStyle(
                            x => x.FontSize(10));

                        page.Header()
                            .Element(x =>
                                ComposeHeader(
                                    x,
                                    payslip));

                        page.Content()
                            .Element(x =>
                                ComposeContent(
                                    x,
                                    payslip));

                        page.Footer()
                            .AlignCenter()
                            .Text(text =>
                            {
                                text.Span(
                                    "Generated by Micro ERP");
                            });
                    });
                });

            return document.GeneratePdf();
        }

        private static void ComposeHeader(
            QuestContainer container,
            EmployeePayslipDto payslip)
        {
            container.Column(column =>
            {
                column.Spacing(5);

                column.Item()
                    .AlignCenter()
                    .Text("PAYSLIP")
                    .Bold()
                    .FontSize(20);

                column.Item()
                    .AlignCenter()
                    .Text(
                        $"{payslip.Year}-{payslip.Month:00}")
                    .FontSize(11);

                column.Item()
                    .PaddingTop(10)
                    .LineHorizontal(1);
            });
        }

        private static void ComposeContent(
            QuestContainer container,
            EmployeePayslipDto payslip)
        {
            container.Column(column =>
            {
                column.Spacing(15);

                // Employee Information
                column.Item()
                    .Element(x =>
                        ComposeEmployeeInformation(
                            x,
                            payslip));

                // Salary Summary
                column.Item()
                    .Element(x =>
                        ComposeSalarySummary(
                            x,
                            payslip));

                // Payroll Items
                column.Item()
                    .Element(x =>
                        ComposePayrollItems(
                            x,
                            payslip));

                // Payment Information
                column.Item()
                    .Element(x =>
                        ComposePaymentInformation(
                            x,
                            payslip));

                // Net Salary
                column.Item()
                    .Element(x =>
                        ComposeNetSalary(
                            x,
                            payslip));
            });
        }

        private static void ComposeEmployeeInformation(
         QuestContainer container,
         EmployeePayslipDto payslip)
        {
            container
                .Border(1)
                .Padding(10)
                .Column(column =>
                {
                    column.Item()
                        .Text("EMPLOYEE INFORMATION")
                        .Bold()
                        .FontSize(12);

                    column.Item()
                        .PaddingTop(8)
                        .Row(row =>
                        {
                            row.RelativeItem()
                                .Text(text =>
                                {
                                    text.Span("Employee: ")
                                        .Bold();

                                    text.Span(
                                        payslip.EmployeeName);
                                });

                            row.RelativeItem()
                                .Text(text =>
                                {
                                    text.Span("Employee ID: ")
                                        .Bold();

                                    text.Span(
                                        payslip.EmployeeId
                                            .ToString());
                                });
                        });

                    column.Item()
                        .PaddingTop(5)
                        .Row(row =>
                        {
                            row.RelativeItem()
                                .Text(text =>
                                {
                                    text.Span("Department: ")
                                        .Bold();

                                    text.Span(
                                        payslip.Department);
                                });

                            row.RelativeItem()
                                .Text(text =>
                                {
                                    text.Span("Period: ")
                                        .Bold();

                                    text.Span(
                                        $"{payslip.StartDate:yyyy-MM-dd} " +
                                        $"to {payslip.EndDate:yyyy-MM-dd}");
                                });
                        });
                });
        }

        private static void ComposeSalarySummary(
         QuestContainer container,
         EmployeePayslipDto payslip)
        {
            container.Column(column =>
            {
                column.Item()
                    .Text("SALARY SUMMARY")
                    .Bold()
                    .FontSize(12);

                column.Item()
                    .PaddingTop(8)
                    .Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.ConstantColumn(120);
                        });

                        AddSummaryRow(
                            table,
                            "Gross Salary",
                            payslip.GrossSalary);

                        AddSummaryRow(
                            table,
                            "Total Allowances",
                            payslip.TotalAllowances);

                        AddSummaryRow(
                            table,
                            "Total Overtime",
                            payslip.TotalOvertime);

                        AddSummaryRow(
                            table,
                            "Total Deductions",
                            payslip.TotalDeductions);
                    });
            });
        }

        private static void AddSummaryRow(
         TableDescriptor table,
         string label,
         decimal amount)
        {
            table.Cell()
                .BorderBottom(1)
                .Padding(5)
                .Text(label);

            table.Cell()
                .BorderBottom(1)
                .Padding(5)
                .AlignRight()
                .Text(amount.ToString("N2"));
        }

        private static void ComposePayrollItems(
    QuestContainer container,
    EmployeePayslipDto payslip)
        {
            container.Column(column =>
            {
                column.Item()
                    .Text("PAYROLL ITEMS")
                    .Bold()
                    .FontSize(12);

                column.Item()
                    .PaddingTop(8)
                    .Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(2);
                            columns.RelativeColumn(2);
                            columns.RelativeColumn();
                        });

                        table.Header(header =>
                        {
                            header.Cell()
                                .Background(Colors.Grey.Lighten2)
                                .Padding(6)
                                .Text("Item")
                                .Bold();

                            header.Cell()
                                .Background(Colors.Grey.Lighten2)
                                .Padding(6)
                                .Text("Type")
                                .Bold();

                            header.Cell()
                                .Background(Colors.Grey.Lighten2)
                                .Padding(6)
                                .AlignRight()
                                .Text("Amount")
                                .Bold();
                        });

                        foreach (var item in payslip.Items)
                        {
                            var type =
                                item.Source == PayrollItemSource.Overtime
                                    ? "Overtime"
                                    : item.Type.ToString();

                            table.Cell()
                                .BorderBottom(1)
                                .Padding(5)
                                .Text(item.ItemName);

                            table.Cell()
                                .BorderBottom(1)
                                .Padding(5)
                                .Text(type);

                            table.Cell()
                                .BorderBottom(1)
                                .Padding(5)
                                .AlignRight()
                                .Text(item.Amount.ToString("N2"));
                        }
                    });
            });
        }

        private static void ComposePaymentInformation(
         QuestContainer container,
         EmployeePayslipDto payslip)
        {
            container
                .Border(1)
                .Padding(10)
                .Column(column =>
                {
                    column.Item()
                        .Text("PAYMENT INFORMATION")
                        .Bold()
                        .FontSize(12);

                    column.Item()
                        .PaddingTop(8)
                        .Text(text =>
                        {
                            text.Span("Status: ")
                                .Bold();

                            text.Span(
                                payslip.Status.ToString());
                        });

                    column.Item()
                        .PaddingTop(5)
                        .Text(text =>
                        {
                            text.Span("Paid On: ")
                                .Bold();

                            text.Span(
                                payslip.PaidOn?
                                    .ToString("yyyy-MM-dd HH:mm")
                                ?? "-");
                        });

                    column.Item()
                        .PaddingTop(5)
                        .Text(text =>
                        {
                            text.Span("Bank: ")
                                .Bold();

                            text.Span(
                                payslip.BankName ?? "-");
                        });

                    column.Item()
                        .PaddingTop(5)
                        .Text(text =>
                        {
                            text.Span("Account Number: ")
                                .Bold();

                            text.Span(
                                payslip.BankAccountNumber ?? "-");
                        });

                    column.Item()
                        .PaddingTop(5)
                        .Text(text =>
                        {
                            text.Span("IBAN: ")
                                .Bold();

                            text.Span(
                                payslip.IBAN ?? "-");
                        });
                });
        }

        private static void ComposeNetSalary(
         QuestContainer container,
        EmployeePayslipDto payslip)
        {
            container
                .Border(2)
                .Padding(12)
                .Row(row =>
                {
                    row.RelativeItem()
                        .Text("NET SALARY")
                        .Bold()
                        .FontSize(15);

                    row.ConstantItem(150)
                        .AlignRight()
                        .Text(
                            payslip.NetSalary.ToString("N2"))
                        .Bold()
                        .FontSize(15);
                });
        }

    }

  }
