using MicroERP.Application.Features.Payrolls.Reports.DTOs;
using MicroERP.Application.Features.Payrolls.Reports.Interfaces;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestContainer = QuestPDF.Infrastructure.IContainer;

namespace MicroERP.Application.Features.Payrolls.Reports.Queries
{
    public class PayrollSummaryPdfService
        : IPayrollSummaryPdfService
    {
        private readonly IPayrollReportQueries _queries;

        public PayrollSummaryPdfService(
        IPayrollReportQueries queries)
        {
            _queries = queries;
        }

        public async Task<byte[]> GenerateAsync(
        PayrollSummaryFilterDto filter,
        CancellationToken cancellationToken = default)
        {
            var result =
                await _queries.GetPayrollSummaryAsync(
                    filter,
                    cancellationToken);

            if (!result.Success || result.Data == null)
            {
                throw new InvalidOperationException(
                    result.Message ??
                    "Payroll summary was not found.");
            }

            var data = result.Data;

            var document =
                Document.Create(container =>
                {
                    container.Page(page =>
                    {
                        page.Size(PageSizes.A4.Landscape());

                        page.Margin(30);

                        page.DefaultTextStyle(
                            x => x.FontSize(9));

                        page.Header()
                            .Element(x =>
                                ComposeHeader(x, data));

                        page.Content()
                            .Element(x =>
                                ComposeContent(x, data));

                        page.Footer()
                            .AlignCenter()
                            .Text("Generated by Micro ERP");
                    });
                });

            return document.GeneratePdf();
        }

        private static void ComposeHeader(
        QuestContainer container,
        PayrollSummaryReportDto data)
        {
            container.Column(column =>
            {
                column.Spacing(5);

                column.Item()
                    .AlignCenter()
                    .Text("PAYROLL SUMMARY")
                    .Bold()
                    .FontSize(20);

                column.Item()
                .AlignCenter()
                .Text($"{data.Year}-{data.Month:00}")
                .FontSize(11);

                column.Item()
                    .PaddingTop(10)
                    .LineHorizontal(1);
            });
        }


        private static void ComposeContent(
        QuestContainer container,
        PayrollSummaryReportDto data)
        {
            container.Column(column =>
            {
                column.Spacing(15);

                column.Item()
                    .Element(x =>
                        ComposePayrollTable(
                            x,
                            data));
            });
        }

        private static void ComposePayrollTable(
        QuestContainer container,
        PayrollSummaryReportDto data)
        {
            container.Column(column =>
            {
                column.Item()
                    .Text("PAYROLL DETAILS")
                    .Bold()
                    .FontSize(12);

                column.Item()
                    .PaddingTop(8)
                    .Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(2.2f);
                            columns.RelativeColumn(1.7f);
                            columns.RelativeColumn(1.2f);
                            columns.RelativeColumn(1.2f);
                            columns.RelativeColumn(1.2f);
                            columns.RelativeColumn(1.1f);
                            columns.RelativeColumn(1.2f);
                            columns.RelativeColumn(1.0f);
                        });

                        table.Header(header =>
                        {
                            header.Cell()
                                .Background(Colors.Grey.Lighten2)
                                .Padding(6)
                                .AlignCenter()
                                .Text("Employee")
                                .Bold();

                            header.Cell()
                                .Background(Colors.Grey.Lighten2)
                                .Padding(6)
                                .AlignCenter()
                                .Text("Department")
                                .Bold();

                            header.Cell()
                                .Background(Colors.Grey.Lighten2)
                                .Padding(6)
                                .AlignCenter()
                                .Text("Gross")
                                .Bold();

                            header.Cell()
                                .Background(Colors.Grey.Lighten2)
                                .Padding(6)
                                .AlignCenter()
                                .Text("Allowances")
                                .Bold();

                            header.Cell()
                                .Background(Colors.Grey.Lighten2)
                                .Padding(6)
                                .AlignCenter()
                                .Text("Overtime")
                                .Bold();

                            header.Cell()
                                .Background(Colors.Grey.Lighten2)
                                .Padding(6)
                                .AlignCenter()
                                .Text("Deductions")
                                .Bold();

                            header.Cell()
                                .Background(Colors.Grey.Lighten2)
                                .Padding(6)
                                .AlignCenter()
                                .Text("Net Salary")
                                .Bold();

                            header.Cell()
                                .Background(Colors.Grey.Lighten2)
                                .Padding(6)
                                .AlignCenter()
                                .Text("Status")
                                .Bold();
                        });
                        foreach (var payroll in data.Payrolls)
                        {
                            AddBodyCell(
                                table,
                                payroll.EmployeeName);

                            AddBodyCell(
                                table,
                                payroll.Department);

                            AddAmountCell(
                                table,
                                payroll.GrossSalary);

                            AddAmountCell(
                                table,
                                payroll.TotalAllowances);

                            AddAmountCell(
                                table,
                                payroll.TotalOvertime);

                            AddAmountCell(
                                table,
                                payroll.TotalDeductions);

                            AddAmountCell(
                                table,
                                payroll.NetSalary);

                            AddBodyCell(
                                table,
                                payroll.Status.ToString());
                        }

                        // TOTAL
                        table.Cell()
                            .ColumnSpan(2)
                            .Background(Colors.Grey.Lighten2)
                            .Padding(6)
                            .Text("TOTAL")
                            .Bold();

                        AddAmountCell(
                            table,
                            data.TotalGrossSalary,
                            true);

                        AddAmountCell(
                            table,
                            data.TotalAllowances,
                            true);

                        AddAmountCell(
                            table,
                            data.TotalOvertime,
                            true);

                        AddAmountCell(
                            table,
                            data.TotalDeductions,
                            true);

                        AddAmountCell(
                            table,
                            data.TotalNetSalary,
                            true);

                        table.Cell()
                            .Background(Colors.Grey.Lighten2)
                            .Padding(6);
                    });
            });
        }


        private static void AddBodyCell(
        TableDescriptor table,
        string? value)
        {
            table.Cell()
                .BorderBottom(1)
                .Padding(5)
                .Text(value ?? "-");
        }

        private static void AddAmountCell(
        TableDescriptor table,
        decimal amount,
        bool bold = false)
        {
            var cell = table.Cell()
                .BorderBottom(1)
                .Padding(5)
                .AlignRight();

            if (bold)
                cell.Text(amount.ToString("N2")).Bold();
            else
                cell.Text(amount.ToString("N2"));
        }

  

    }
}