using MicroERP.Application.Features.Payrolls.Reports.DTOs;
using MicroERP.Application.Features.Payrolls.Reports.Interfaces;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestContainer = QuestPDF.Infrastructure.IContainer;

namespace MicroERP.Application.Features.Payrolls.Reports.Queries;

public class PayrollStatisticsPdfService
    : IPayrollStatisticsPdfService
{
    private readonly IPayrollReportQueries _queries;

    public PayrollStatisticsPdfService(
        IPayrollReportQueries queries)
    {
        _queries = queries;
    }

    public async Task<byte[]> GenerateAsync(
        PayrollStatisticsFilterDto filter,
        CancellationToken cancellationToken = default)
    {
        var result =
            await _queries.GetPayrollStatisticsAsync(
                filter,
                cancellationToken);

        if (!result.Success || result.Data == null)
        {
            throw new InvalidOperationException(
                result.Message ??
                "Payroll statistics were not found.");
        }

        var data = result.Data;

        var document =
            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);

                    page.Margin(35);

                    page.DefaultTextStyle(
                        x => x.FontSize(10));

                    page.Header()
                        .Element(x =>
                            ComposeHeader(
                                x,
                                data));

                    page.Content()
                        .Element(x =>
                            ComposeContent(
                                x,
                                data));

                    page.Footer()
                        .AlignCenter()
                        .Text(
                            "Generated by Micro ERP");
                });
            });

        return document.GeneratePdf();
    }

    private static void ComposeHeader(
        QuestContainer container,
        PayrollStatisticsDto data)
    {
        container.Column(column =>
        {
            column.Spacing(5);

            column.Item()
                .AlignCenter()
                .Text("PAYROLL STATISTICS")
                .Bold()
                .FontSize(20);

            column.Item()
                .AlignCenter()
                .Text(data.Period)
                .FontSize(11);

            column.Item()
                .PaddingTop(10)
                .LineHorizontal(1);
        });
    }

    private static void ComposeContent(
        QuestContainer container,
        PayrollStatisticsDto data)
    {
        container.Column(column =>
        {
            column.Spacing(15);

            column.Item()
                .Element(x =>
                    ComposeEmployeeStatistics(
                        x,
                        data));

            column.Item()
                .Element(x =>
                    ComposeSalaryStatistics(
                        x,
                        data));

            column.Item()
                .Element(x =>
                    ComposeSalaryRange(
                        x,
                        data));
        });
    }

    private static void ComposeEmployeeStatistics(
        QuestContainer container,
        PayrollStatisticsDto data)
    {
        container.Column(column =>
        {
            column.Item()
                .Text("EMPLOYEE STATISTICS")
                .Bold()
                .FontSize(12);

            column.Item()
                .PaddingTop(8)
                .Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn();
                        columns.RelativeColumn();
                        columns.RelativeColumn();
                        columns.RelativeColumn();
                    });

                    AddKpiCell(
                        table,
                        "Employees",
                        data.EmployeesCount.ToString());

                    AddKpiCell(
                        table,
                        "Draft",
                        data.DraftEmployeesCount.ToString());

                    AddKpiCell(
                        table,
                        "Calculated",
                        data.CalculatedEmployeesCount.ToString());

                    AddKpiCell(
                        table,
                        "Approved",
                        data.ApprovedEmployeesCount.ToString());

                    AddKpiCell(
                        table,
                        "Paid",
                        data.PaidEmployeesCount.ToString());
                });
        });
    }

    private static void ComposeSalaryStatistics(
        QuestContainer container,
        PayrollStatisticsDto data)
    {
        container.Column(column =>
        {
            column.Item()
                .Text("SALARY STATISTICS")
                .Bold()
                .FontSize(12);

            column.Item()
                .PaddingTop(8)
                .Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(2);
                        columns.RelativeColumn();
                    });

                    AddStatisticRow(
                        table,
                        "Gross Salary",
                        data.TotalGrossSalary);

                    AddStatisticRow(
                        table,
                        "Total Allowances",
                        data.TotalAllowances);

                    AddStatisticRow(
                        table,
                        "Total Overtime",
                        data.TotalOvertime);

                    AddStatisticRow(
                        table,
                        "Total Deductions",
                        data.TotalDeductions);

                    AddStatisticRow(
                        table,
                        "Total Net Salary",
                        data.TotalNetSalary);

                    AddStatisticRow(
                        table,
                        "Average Net Salary",
                        data.AverageNetSalary);
                });
        });
    }

    private static void ComposeSalaryRange(
        QuestContainer container,
        PayrollStatisticsDto data)
    {
        container
            .Border(1)
            .Padding(10)
            .Column(column =>
            {
                column.Item()
                    .Text("SALARY RANGE")
                    .Bold()
                    .FontSize(12);

                column.Item()
                    .PaddingTop(8)
                    .Row(row =>
                    {
                        row.RelativeItem()
                            .Text(text =>
                            {
                                text.Span("Lowest Net Salary: ")
                                    .Bold();

                                text.Span(
                                    data.LowestNetSalary
                                        .ToString("N2"));
                            });

                        row.RelativeItem()
                            .Text(text =>
                            {
                                text.Span("Highest Net Salary: ")
                                    .Bold();

                                text.Span(
                                    data.HighestNetSalary
                                        .ToString("N2"));
                            });
                    });
            });
    }

    private static void AddKpiCell(
        TableDescriptor table,
        string label,
        string value)
    {
        table.Cell()
            .Border(1)
            .Padding(10)
            .AlignCenter()
            .Column(column =>
            {
                column.Item()
                    .Text(label)
                    .Bold()
                    .FontSize(9);

                column.Item()
                    .PaddingTop(5)
                    .Text(value)
                    .Bold()
                    .FontSize(15);
            });
    }

    private static void AddStatisticRow(
        TableDescriptor table,
        string label,
        decimal amount)
    {
        table.Cell()
            .BorderBottom(1)
            .Padding(6)
            .Text(label);

        table.Cell()
            .BorderBottom(1)
            .Padding(6)
            .AlignRight()
            .Text(amount.ToString("N2"))
            .Bold();
    }
}