using MicroERP.Application.Features.Payrolls.Reports.DTOs;
using MicroERP.Application.Features.Payrolls.Reports.Interfaces;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestContainer = QuestPDF.Infrastructure.IContainer;

namespace MicroERP.Application.Features.Payrolls.Reports.Queries;

public class PayrollDetailsPdfService
    : IPayrollDetailsPdfService
{
    private readonly IPayrollReportQueries _queries;

    public PayrollDetailsPdfService(
        IPayrollReportQueries queries)
    {
        _queries = queries;
    }

    public async Task<byte[]> GenerateAsync(
        PayrollDetailsFilterDto filter,
        CancellationToken cancellationToken = default)
    {
        var result =
            await _queries.GetPayrollDetailsAsync(
                filter,
                cancellationToken);

        if (!result.Success || result.Data == null)
        {
            throw new InvalidOperationException(
                result.Message ??
                "Payroll details were not found.");
        }

        var data = result.Data;

        var document =
            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4.Landscape());

                    page.Margin(25);

                    page.DefaultTextStyle(
                        x => x.FontSize(10));

                    page.Header()
                        .Element(x =>
                            ComposeHeader(x, data));

                    page.Content()
                        .Element(x =>
                            ComposeContent(x, data));

                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by Micro ERP");
                });
            });

        return document.GeneratePdf();
    }

    private static void ComposeHeader(
        QuestContainer container,
        PayrollDetailsDto data)
    {
        container.Column(column =>
        {
            column.Spacing(5);

            column.Item()
                .AlignCenter()
                .Text("PAYROLL DETAILS")
                .Bold()
                .FontSize(18);

            column.Item()
                .AlignCenter()
                .Text(data.Period)
                .FontSize(11);

            column.Item()
                .PaddingTop(10)
                .LineHorizontal(1);
        });
    }

    private static void ComposeContent(
        QuestContainer container,
        PayrollDetailsDto data)
    {
        container.Column(column =>
        {
            column.Spacing(15);

            column.Item()
                .Element(x =>
                    ComposeEmployeeInformation(x, data));

            column.Item()
                .Element(x =>
                    ComposeSalarySummary(x, data));

            column.Item()
                .Element(x =>
                    ComposePayrollItems(x, data));

            column.Item()
                .Element(x =>
                    ComposeApprovalInformation(x, data));

            column.Item()
                .Element(x =>
                    ComposePaymentInformation(x, data));

            column.Item()
                .Element(x =>
                    ComposeNetSalary(x, data));
        });
    }

    private static void ComposeEmployeeInformation(
        QuestContainer container,
        PayrollDetailsDto data)
    {
        container
            .Border(1)
            .Padding(10)
            .Column(column =>
            {
                column.Item()
                    .Text("EMPLOYEE INFORMATION")
                    .Bold()
                    .FontSize(12);

                column.Item()
                    .PaddingTop(8)
                    .Row(row =>
                    {
                        row.RelativeItem()
                            .Text(text =>
                            {
                                text.Span("Employee: ")
                                    .Bold();

                                text.Span(data.EmployeeName);
                            });

                        row.RelativeItem()
                            .Text(text =>
                            {
                                text.Span("Employee ID: ")
                                    .Bold();

                                text.Span(
                                    data.EmployeeId.ToString());
                            });
                    });

                column.Item()
                    .PaddingTop(5)
                    .Row(row =>
                    {
                        row.RelativeItem()
                            .Text(text =>
                            {
                                text.Span("Department: ")
                                    .Bold();

                                text.Span(data.Department);
                            });

                        row.RelativeItem()
                            .Text(text =>
                            {
                                text.Span("Period: ")
                                    .Bold();

                                text.Span(data.Period);
                            });
                    });

                column.Item()
                    .PaddingTop(5)
                    .Text(text =>
                    {
                        text.Span("Status: ")
                            .Bold();

                        text.Span(
                            data.Status.ToString());
                    });
            });
    }

    private static void ComposeSalarySummary(
        QuestContainer container,
        PayrollDetailsDto data)
    {
        container.Column(column =>
        {
            column.Item()
                .Text("SALARY SUMMARY")
                .Bold()
                .FontSize(12);

            column.Item()
                .PaddingTop(8)
                .Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn();
                        columns.ConstantColumn(130);
                    });

                    AddSummaryRow(
                        table,
                        "Gross Salary",
                        data.GrossSalary);

                    AddSummaryRow(
                        table,
                        "Total Allowances",
                        data.TotalAllowances);

                    AddSummaryRow(
                        table,
                        "Total Overtime",
                        data.TotalOvertime);

                    AddSummaryRow(
                        table,
                        "Total Deductions",
                        data.TotalDeductions);
                });
        });
    }

    private static void ComposePayrollItems(
        QuestContainer container,
        PayrollDetailsDto data)
    {
        container.Column(column =>
        {
            column.Item()
                .Text("PAYROLL COMPONENTS")
                .Bold()
                .FontSize(12);

            column.Item()
                .PaddingTop(8)
                .Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(2.5f);
                        columns.RelativeColumn(1.2f);
                        columns.RelativeColumn();
                    });

                    table.Header(header =>
                    {
                        header.Cell()
                            .Background(Colors.Grey.Lighten2)
                            .Padding(6)
                            .Text("Component")
                            .Bold();

                        header.Cell()
                            .Background(Colors.Grey.Lighten2)
                            .Padding(6)
                            .Text("Type")
                            .Bold();

                        header.Cell()
                            .Background(Colors.Grey.Lighten2)
                            .Padding(6)
                            .AlignRight()
                            .Text("Amount")
                            .Bold();
                    });

                    foreach (var item in data.Items)
                    {
                        table.Cell()
                            .BorderBottom(1)
                            .Padding(5)
                            .Text(item.ComponentName);

                        table.Cell()
                            .BorderBottom(1)
                            .Padding(5)
                            .Text(
                                item.Type.ToString());

                        table.Cell()
                            .BorderBottom(1)
                            .Padding(5)
                            .AlignRight()
                            .Text(
                                item.Amount.ToString("N2"));
                    }
                });
        });
    }

    private static void ComposeApprovalInformation(
        QuestContainer container,
        PayrollDetailsDto data)
    {
        container
            .Border(1)
            .Padding(10)
            .Column(column =>
            {
                column.Item()
                    .Text("APPROVAL INFORMATION")
                    .Bold()
                    .FontSize(12);

                column.Item()
                    .PaddingTop(8)
                    .Text(text =>
                    {
                        text.Span("Approved On: ")
                            .Bold();

                        text.Span(
                            data.ApprovedOn?
                                .ToString("yyyy-MM-dd HH:mm")
                            ?? "-");
                    });

                column.Item()
                    .PaddingTop(5)
                    .Text(text =>
                    {
                        text.Span("Approved By: ")
                            .Bold();

                        text.Span(
                            data.ApprovedByUserName ?? "-");
                    });
            });
    }

    private static void ComposePaymentInformation(
        QuestContainer container,
        PayrollDetailsDto data)
    {
        container
            .Border(1)
            .Padding(10)
            .Column(column =>
            {
                column.Item()
                    .Text("PAYMENT INFORMATION")
                    .Bold()
                    .FontSize(12);

                column.Item()
                    .PaddingTop(8)
                    .Text(text =>
                    {
                        text.Span("Paid On: ")
                            .Bold();

                        text.Span(
                            data.PaidOn?
                                .ToString("yyyy-MM-dd HH:mm")
                            ?? "-");
                    });

                column.Item()
                    .PaddingTop(5)
                    .Text(text =>
                    {
                        text.Span("Paid By: ")
                            .Bold();

                        text.Span(
                            data.PaidByUserName ?? "-");
                    });

                column.Item()
                    .PaddingTop(5)
                    .Text(text =>
                    {
                        text.Span("Bank: ")
                            .Bold();

                        text.Span(
                            data.BankName ?? "-");
                    });

                column.Item()
                    .PaddingTop(5)
                    .Text(text =>
                    {
                        text.Span("Account Number: ")
                            .Bold();

                        text.Span(
                            data.BankAccountNumber ?? "-");
                    });

                column.Item()
                    .PaddingTop(5)
                    .Text(text =>
                    {
                        text.Span("IBAN: ")
                            .Bold();

                        text.Span(
                            data.IBAN ?? "-");
                    });
            });
    }

    private static void ComposeNetSalary(
        QuestContainer container,
        PayrollDetailsDto data)
    {
        container
            .Border(2)
            .Padding(12)
            .Row(row =>
            {
                row.RelativeItem()
                    .Text("NET SALARY")
                    .Bold()
                    .FontSize(12);

                row.ConstantItem(150)
                    .AlignRight()
                    .Text(
                        data.NetSalary.ToString("N2"))
                    .Bold()
                    .FontSize(15);
            });
    }

    private static void AddSummaryRow(
        TableDescriptor table,
        string label,
        decimal amount)
    {
        table.Cell()
            .BorderBottom(1)
            .Padding(5)
            .Text(label);

        table.Cell()
            .BorderBottom(1)
            .Padding(5)
            .AlignRight()
            .Text(amount.ToString("N2"));
    }
}